name: test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0"
          gleam-version: "1.4.0"
          rebar3-version: "3"
          elixir-version: "1.15"
      - name: Install dependencies
        run: gleam deps download
      - name: Run tests
        run: gleam test
